import { Palette } from "Palette.slint";

export component BaseButton {
    property <bool> pressed: false;
    in-out property <string> content: "0";
    in-out property <length> button-width;
    in-out property <length> button-height;
    in-out property <length> in-font-size: 20px;
    in-out property <bool> border-shown: true;
    in-out property <color> text-color: pressed && !border-shown ? Palette.green : Palette.black;
    in-out property <color> background-color: pressed && border-shown ? Palette.green : transparent;
    Rectangle {
        width: button-width;
        height: button-height;
        border-color: border-shown ? Palette.black : transparent;
        border-width: border-shown ? 2px : 0px;
        border-radius: self.width/300;
        background: root.background-color;
        text := Text {
            text: content;
            font-size: root.in-font-size;
            color: root.text-color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
        TouchArea {
            width: root.button-width;
            height: root.button-height;
            pointer-event(event) => {
                if (event.kind == PointerEventKind.down) {
                    pressed = true;
                } else if (event.kind == PointerEventKind.up) {
                    pressed = false;
                    root.clicked();
                    debug("Clicked pin", content);
                }
            }
        }
    }
    callback clicked();
}