import { HitoWindow } from "HitoWindow.slint";
import { Palette } from "Palette.slint";
import { BaseButton } from "BaseButton.slint";

export component HomeScreen inherits HitoWindow {
    // Indicate this is not the lock screen
    is-lockscreen: false;
    show-brightness: true; // Show brightness control on home screen

    // Title text
    Text {
        text: "Home Screen";
        font-size: 24px;
        color: black;
        horizontal-alignment: center;
        y: 100px;
        width: parent.width;
    }
    HorizontalLayout {
      x: 10px;
      y: 160px;
      width: 300px;
      height: 50px;
      spacing: 10px;
        BaseButton { 
          content: "Receive";
          button-width: 125px;
          button-height: 50px;
        }
        BaseButton { 
          content: "Send";
          button-width: 125px;
          button-height: 50px;
        }
    }
  callback clicked();
}