import { LockScreen } from "LockScreen.slint";
import { TestScreen } from "TestScreen.slint";
import { Router, Screen } from "Router.slint";

import { BrightnessController } from "BrightnessController.slint";

export { BrightnessController }

export component MainWindow inherits Window {
    width: 320px;
    height: 240px;

    // Main navigation container
    if Router.current == Screen.Lock: LockScreen {}
    if Router.current == Screen.TestScreen: TestScreen {}
}