import {TestScreen2View} from "TestScreen2.slint";
import {BaseButton} from "BaseButton.slint";
    

component BlockchainNetworkButton {
    in-out property <string> content;
    in-out property <image> img-url;
    VerticalLayout {
      Image {
          source: img-url;
          height: 58px;
      }
      Text {
          text: content;
      }
    }
}

export component ReceiveScreenView {
    width: 320px;
    height: 240px;
    VerticalLayout {
      y: 20px;
        HorizontalLayout {
            alignment: center;
            BlockchainNetworkButton {
                content: "Bitcoin";
                img-url: @image-url("../../res/img/btc_logo.png");
            }
            BlockchainNetworkButton {
                content: "Ethereum";
                img-url: @image-url("../../res/img/eth_logo.png");
            }
        }
        HorizontalLayout {
            alignment: center;
        }
    }
}