// Global router state
export enum ScreenEnum {
    Lock, 
    TestScreen,
    EnterPin, 
    TestScreen2, 
    Home,
    Send,
    Receive,
    Settings,
    PairWithTheApp,
    DeviceInfo,
}

export global Router {
    callback navigate(page: ScreenEnum);
    in-out property <ScreenEnum> current: ScreenEnum.Lock;
    callback back();

    // Handle navigation
    navigate(to) => {
        current = to;
    }
    back() => {
        // Simple back navigation logic
        if current == ScreenEnum.Send || current == ScreenEnum.Receive || current == ScreenEnum.Settings {
            current = ScreenEnum.Home;
        }
        else if current == ScreenEnum.PairWithTheApp || current == ScreenEnum.DeviceInfo {
            current = ScreenEnum.Settings;
        }
        else {
            current = ScreenEnum.Lock;
        }
    }
}