import { TestScreen2View } from "TestScreen2.slint";
import { HitoWindow } from "HitoWindow.slint";
import { Palette } from "Palette.slint";
import { BaseButton } from "BaseButton.slint";
import { Spacer } from "Spacer.slint";
import { Router, ScreenEnum } from "Router.slint";
import { DeviceInfoController } from "DeviceInfoController.slint";

component SettingsOptionButton inherits BaseButton {
    button-width: 240px;
    button-height: 30px;
    border-shown: false;
    text-color-pressed: Palette.black;
    text-color-unpressed: Palette.blue;
    // background-color-unpressed: transparent;
    // background-color-pressed: Palette.green;
    border-color: Palette.green;
    border-radius: 10px;
}

export component SettingsScreenView {
    width: 320px;
    height: 240px;
    VerticalLayout {
        width: 320px;
        alignment: start;
        y: 35px;
        spacing: 10px;
        SettingsOptionButton {
            content: "Pair with the app";
            clicked => {
                Router.navigate(ScreenEnum.PairWithTheApp);
            }
        }
        SettingsOptionButton {
            content: "Show seed phrase";
            clicked => {
                Router.navigate(ScreenEnum.Send);
            }
        }
        SettingsOptionButton {
            content: "Device info";
            clicked => {
                Router.navigate(ScreenEnum.DeviceInfo);
            }
        }
        Spacer { height: 2px; }
        SettingsOptionButton {
            content: "Change passcode";
            clicked => {
                Router.navigate(ScreenEnum.Send);
            }
        }
        SettingsOptionButton {
            content: "Factory reset";
            clicked => {
                Router.navigate(ScreenEnum.Send);
            }
        }
    }
    // Additional UI elements for the Settings screen can be added here
}