import { HitoWindow } from "HitoWindow.slint";
import { Router } from "Router.slint";
import "../../res/fonts/RobotoMono-Light.ttf";

export component TestScreen2 inherits HitoWindow {
    header-title: "Test Screen 2";
    Text {
        text: "Test screen 2!)";
        font-size: 20px;
        color: black;
        horizontal-alignment: center;
        font-family: "Roboto Mono";
        y: 120px;
        x: 30px;
        wrap: word-wrap;
        width: 260px;
    }
}