import { HitoWindow } from "HitoWindow.slint";
import { Router } from "Router.slint";
import "../../res/fonts/RobotoMono.ttf";

export component TestScreen2View {
    width: 320px;
    height: 240px;
    Text {
        text: "Test screen !)";
        font-size: 20px;
        color: black;
        horizontal-alignment: center;
        font-family: "Roboto Mono";
        y: 120px;
        x: 30px;
        wrap: word-wrap;
        width: 260px;
    }
}