import { HitoWindow } from "HitoWindow.slint";
import { Router, Screen } from "Router.slint";
import "../../res/fonts/RobotoMono-Light.ttf";

export component TestScreen inherits HitoWindow {
    Text {
        text: "Test screen!)";
        font-size: 20px;
        color: black;
        horizontal-alignment: center;
        y: 120px;
        x: 30px;
        wrap: word-wrap;
        width: 260px;
    }
}