import { Palette } from "Palette.slint";

export component BaseButton {
    in-out property <bool> pressed: false;
    in-out property <string> content: "0";
    in-out property <length> button-width;
    in-out property <length> button-height;
    in-out property <length> in-font-size: 20px;
    in-out property <color> text-color-unpressed: Palette.black;
    in-out property <color> text-color-pressed: Palette.blue;
    in-out property <color> background-color-unpressed: transparent;
    in-out property <color> background-color-pressed: Palette.blue;
    in-out property <color> border-color-pressed: Palette.blue;
    in-out property <color> border-color-unpressed: Palette.black;
    in-out property <length> border-width: 2px;
    in-out property <length> border-radius: 0px;
    Rectangle {
        width: button-width;
        height: button-height;
        border-color: pressed ? border-color-pressed : border-color-unpressed;
        border-width: border-width;
        border-radius: border-radius;
        background: pressed ? background-color-pressed : background-color-unpressed;
        Text {
            text: content;
            font-size: root.in-font-size;
            color: pressed ? text-color-pressed : text-color-unpressed;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
        TouchArea {
            width: root.button-width;
            height: root.button-height;
            pointer-event(event) => {
                if (event.kind == PointerEventKind.down) {
                    pressed = true;
                } else if (event.kind == PointerEventKind.up) {
                    pressed = false;
                    root.clicked();
                    debug("Clicked pin", content);
                }
            }
        }
    }
    callback clicked();
}