import { Spacer } from "Spacer.slint";
import { Palette } from "Palette.slint";

export global DeviceInfoState {
    in-out property <string> firmware-version;
    in-out property <string> bootloader-version;
    in-out property <string> serial-number;
    callback request-device-info();
    in-out property <string> factory-reset-string;
}

export component DeviceInfoScreenView {
    // Indicate this is not the lock screen
    //header-title: "DEVICE INFO";
    width: 320px;
    height: 240px;
    Text {
        text: "Firmware: " + DeviceInfoState.firmware-version;
        font-size: 20px;
        y: 60px;
        //font-weight: 600;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: #000000;
    }
    Text {
        text: "Bootloader: " + DeviceInfoState.bootloader-version;
        font-size: 20px;
        y: 85px;
        //font-weight: 600;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: #000000;
    }
    Spacer { height: 10px; }
    Text {
        text: "Serial number";
        font-size: 20px;
        y: 120px;
        //font-weight: 600;
        color: #000000;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
    Text {
        text: DeviceInfoState.serial-number;
        font-size: 20px;
        y: 145px;
        //font-weight: 600;
        color: Palette.blue;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
    Spacer { height: 5px; }
    Text {
        text: DeviceInfoState.factory-reset-string;
        font-size: 20px;
        y: 180px;
        //font-weight: 600;
        color: #000000;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
}