import { Spacer } from "Spacer.slint";
import { Palette } from "Palette.slint";

export global DeviceInfoState {
    in-out property <string> firmware-version;
    in-out property <string> bootloader-version;
    in-out property <string> serial-number;
    in-out property <int> factory-reset-count: 0;
    callback request-device-info();
    callback request-factory-reset-string();
    in-out property <string> factory-reset-string: {
      if factory-reset-count < 0 {
          "Factory reset no data";
      } else if factory-reset-count == 0 {
          "Factory setup";
      } else if factory-reset-count > 30 {
          "Factory reset 30+ times";
      } else {
          "Factory reset " + (factory-reset-count - 1) + " times";
      }
    }
}

export component DeviceInfoScreenView {
    // Indicate this is not the lock screen
    //header-title: "DEVICE INFO";
    width: 320px;
    height: 240px;
    HorizontalLayout {
      // width: parent.width;
      // height: parent.height;
      alignment: center;
    VerticalLayout {
        // width: parent.width;
        // height: parent.height;
        alignment: start;
        padding-top: 60px; 

        Text {
            text: "Firmware: " + DeviceInfoState.firmware-version;
            font-size: 20px;
            //font-weight: 600;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #000000;
        }
        Text {
            text: "Bootloader: " + DeviceInfoState.bootloader-version;
            font-size: 20px;
            //font-weight: 600;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #000000;
        }
        Spacer { height: 10px; }
        Text {
            text: "Serial number";
            font-size: 20px;
            //font-weight: 600;
            color: #000000;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
        Text {
            text: DeviceInfoState.serial-number;
            font-size: 20px;
            //font-weight: 600;
            color: Palette.blue;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
        Spacer { height: 5px; }
        Text {
            text: DeviceInfoState.factory-reset-string;
            font-size: 20px;
            //font-weight: 600;
            color: #000000;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
    }
}