import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
export global EnterPinController {
  in-out property <int> decoding-progress: -1; // -1 means no progress
  in-out property <bool> wrong-passcode;
  callback append-char(digit: int);
  callback remove-char();
  callback passcode-entered();
  callback unlock(result: bool);
  callback progress-request();
  callback set-progress(progress: int);
  callback reset();
  unlock(result) => {
      if !result {
          wrong-passcode = true;
      } else if Router.previous == ScreenEnum.Lock {
          Router.navigate(ScreenEnum.Home);
      } else if Router.previous == ScreenEnum.Settings{
          Router.navigate(ScreenEnum.ShowSeed);
      }
      reset();
  }
  set-progress(progress) => {
      debug("Setting decoding progress to", progress);
      decoding-progress = progress;
  }
  reset() => {
      decoding-progress = -1;
      wrong-passcode = false;
  }
}