import { Palette } from "Palette.slint";
import { BaseButton } from "BaseButton.slint";
import { TransparentButton } from "TransparentButton.slint";
import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { ReceiveDataState } from "ReceiveScreen.slint";
import { Spacer } from "Spacer.slint";


component SettingsButtonLine inherits Rectangle {
  width: 27px;
  height: 2px;
  background: Palette.black;
  border-width: 0px;
}

export component SettingsButton {
    in-out property <bool> pressed: false;
    in-out property <string> content: "____";
    in-out property <bool> border-shown: true;
    in-out property <color> text-color-unpressed: Palette.black;
    in-out property <int> touch-area-ratio: 1;
    in-out property <color> text-color-pressed: Palette.blue;
    in-out property <color> border-color: Palette.black;
    in-out property <length> letter-spacing: -2px;
    TouchArea {
        width: root.width * root.touch-area-ratio;
        height: root.height * root.touch-area-ratio;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                pressed = true;
            } else if (event.kind == PointerEventKind.up) {
                pressed = false;
                root.clicked();
                debug("Clicked settings button");
            }
        }
    }
    layout:= VerticalLayout {
      spacing: -3px;
      SettingsButtonLine {
        background: pressed ? Palette.blue : Palette.black;
      }
      Spacer {
        height: 15px;
      }
      SettingsButtonLine {
        background: pressed ? Palette.blue : Palette.black;
      }
    }
    callback clicked();
    clicked() => {
        Router.navigate(ScreenEnum.Settings);
    }
}

export component HomeScreenView {
    // Indicate this is not the lock screen
    // is-lockscreen: false;
    // back-shown: false; // No back button on home screen
    // show-brightness: true; // Show brightness control on home screen
    width: 320px;
    height: 240px;
    HorizontalLayout {
        width: parent.width;
        alignment: start;
        VerticalLayout {
            y: 20px;
            alignment: start;
            SettingsButton {
                touch-area-ratio: 2.5;
                x: 20px;
            }
        }
    }
    HorizontalLayout {
      alignment: center;
      spacing: 30px;
      y: -20px;
      Image {
        source: @image-url("../../../res/img/hito_logo.png");
      }
    }
    HorizontalLayout {
      alignment: start;
      x: 40px;
      y: 175px;
      height: 50px;
      spacing: 90px;
        BaseButton { 
          content: "RECEIVE";
          button-width: 130px;
          button-height: 40px;
          background-color-pressed: transparent;
          background-color-unpressed: transparent;
          text-color-pressed: Palette.blue;
          text-color-unpressed: Palette.black;
          border-color-pressed: Palette.blue;
          border-color-unpressed: Palette.black;
          clicked => {
            ReceiveDataState.request-receive-data();
            Router.navigate(ScreenEnum.Receive);
          }
        }
        BaseButton { 
          content: "SEND";
          button-width: 130px;
          button-height: 40px;
          background-color-pressed: transparent;
          background-color-unpressed: transparent;
          text-color-pressed: Palette.blue;
          text-color-unpressed: Palette.black;
          clicked => {
            Router.navigate(ScreenEnum.Send);
          }
        }
    }
  callback clicked();
}