import { Palette } from "Palette.slint";
import { BaseButton } from "BaseButton.slint";
import { TransparentButton } from "TransparentButton.slint";
import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { ReceiveDataState } from "ReceiveScreen.slint";
import { Spacer } from "Spacer.slint";
import { SendScreenState } from "SendScreen.slint";

component SettingsButtonLine inherits Rectangle {
  width: 27px;
  height: 2px;
  background: Palette.black;
  border-width: 0px;
}

export component SettingsButton {
    in-out property <bool> pressed: false;
    in-out property <string> content: "____";
    in-out property <color> text-color-unpressed: Palette.black;
    in-out property <color> text-color-pressed: Palette.blue;
    in-out property <length> letter-spacing: -2px;
    line1:=SettingsButtonLine {
      y: 5px;
      background: pressed ? Palette.blue : Palette.black;
    }
    line2:=SettingsButtonLine {
      y: 16px;
      background: pressed ? Palette.blue : Palette.black;
    }
    TouchArea {
        x: line1.x - 5px;
        y: line1.y - 5px;
        width: line2.width + 5px;
        height: line2.y + 5px;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                pressed = true;
            } else if (event.kind == PointerEventKind.up) {
                pressed = false;
                root.clicked();
            }
        }
    }
    callback clicked();
    clicked() => {
        Router.navigate(ScreenEnum.Settings);
    }
}

export component HomeScreenView {
    // Indicate this is not the lock screen
    // is-lockscreen: false;
    // back-shown: false; // No back button on home screen
    // show-brightness: true; // Show brightness control on home screen
    width: 320px;
    height: 240px;
    SettingsButton {
      x: 35px;
      y: 15px;
    }
    Image {
      y: 70px;
      source: @image-url("../../../res/img/hito_logo.png");
    }
    BaseButton { 
      content: "RECEIVE";
      x: 40px;
      y: 190px;
      button-width: 130px;
      button-height: 40px;
      background-color-pressed: transparent;
      background-color-unpressed: transparent;
      text-color-pressed: Palette.blue;
      text-color-unpressed: Palette.black;
      border-color-pressed: Palette.blue;
      border-color-unpressed: Palette.black;
      clicked => {
        ReceiveDataState.request-receive-data();
        Router.navigate(ScreenEnum.Receive);
      }
    }
    BaseButton {
      x: 210px;
      y: 190px; 
      content: "SEND";
      button-width: 130px;
      button-height: 40px;
      background-color-pressed: transparent;
      background-color-unpressed: transparent;
      text-color-pressed: Palette.blue;
      text-color-unpressed: Palette.black;
      clicked => {
        Router.navigate(ScreenEnum.Send);
      }
    }
  callback clicked();
}