import {TestScreen2View} from "TestScreen2View.slint";
import { BaseButton } from "BaseButton.slint";
import { ReceiveDataController } from "ReceiveDataController.slint";

export component ReceiveScreenView {
    width: 320px;
    height: 240px;
    VerticalLayout {
      alignment: end;
      y: -10px;
      Text {
          text: ReceiveDataController.address-short;
          font-size: 20px;
          horizontal-alignment: center;
          vertical-alignment: center;
          font-weight: 1000;
      }
    }
    VerticalLayout {
      alignment: center;
      HorizontalLayout {
        alignment: end;
        x: -45px;
        Image {
          source: @image-url("../../../res/img/stellar_logo.png");
          width: 80px;
          height: 80px;
        }
      }
    }
}