import {TestScreen2View} from "TestScreen2.slint";

export global ReceiveDataState {
    in-out property <string> address-short;
    callback request-receive-data();
    in-out property <bool> qr-data-requested: false;
}

export component ReceiveScreenView {
    width: 320px;
    height: 240px;
    VerticalLayout {
      alignment: end;
      y: -10px;
      Text {
          text: ReceiveDataState.address-short;
          font-size: 20px;
          horizontal-alignment: center;
          vertical-alignment: center;
          //font-weight: 1000;
      }
    }
    VerticalLayout {
      alignment: center;
      HorizontalLayout {
        alignment: end;
        x: -45px;
        Image {
          source: @image-url("../../../res/img/stellar_logo.png");
          width: 80px;
          height: 80px;
        }
      }
    }
}