import {TestScreen2View} from "TestScreen2.slint";

export global ReceiveDataState {
    in-out property <string> address-short;
    callback request-receive-data();
    in-out property <bool> qr-data-requested: false;
}

export component ReceiveScreenView {
    width: 320px;
    height: 240px;
    Text {
        y: 200px;
        text: ReceiveDataState.address-short;
        font-size: 20px;
        horizontal-alignment: center;
        vertical-alignment: center;
        //font-weight: 1000;
    }
    init => {
        ReceiveDataState.request-receive-data();
    }
}