import { ScreenEnum } from "ScreenEnum.slint";
import { StartScreen } from "SetStartScreen.slint";

export global Router {
    callback navigate(page: ScreenEnum);
    in-out property <ScreenEnum> current: StartScreen.screen;
    in-out property <ScreenEnum> previous: StartScreen.screen;
    callback back();

    // Handle navigation
    navigate(to) => {
        previous = current;
        current = to;
    }
    back() => {
        // Simple back navigation logic
        if current == ScreenEnum.Send || current == ScreenEnum.Receive || current == ScreenEnum.Settings {
            current = ScreenEnum.Home;
        }
        else if current == ScreenEnum.PairWithTheApp || current == ScreenEnum.DeviceInfo || current == ScreenEnum.ShowSeed {
            current = ScreenEnum.Settings;
        }
        else if current == ScreenEnum.SendStellar {
            current = ScreenEnum.Home;
        }
        else if current == ScreenEnum.ErrorSending {
            current = ScreenEnum.Home;
        }
        else {
            current = ScreenEnum.Lock;
        }
    }
}