import { Router } from "Router.slint";
import { Palette } from "Palette.slint";
import { TransparentButton } from "TransparentButton.slint";

export global SendStellarState {
  in-out property <float> amount: 0.0;
  in-out property <string> destination-short: "";
}

component Spacer inherits Rectangle {
    width: 1px;
    height: 1px;
    background: transparent;
    horizontal-stretch: 1;
    vertical-stretch: 1;
}

export component SendStellarScreenView {
    width: 320px;
    height: 240px;
    HorizontalLayout {
      x: 0px;
      y: 0px;
      alignment: end;
      padding-left: 30px;
      padding-right: 24px;
      padding-top: 45px;
      width: parent.width;
      height: parent.height - 100px;
      VerticalLayout {
        width: 100px;
        height: 100px;
        alignment: start;
        Text {
            text: "Amount:";
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 20px;
            color: black;
        }
        Spacer {
          height: 5px;
        }
        Text {
            text: SendStellarState.amount;
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 20px;
            color: black;
        }
        Spacer {
          height: 5px;
        }
        Text {
            text: "XLM";
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 20px;
            //font-weight: 1000;
            color: black;
        }
        Spacer {
          height: 50px;
        }
        TransparentButton {
            content: "SIGN";
            text-color-pressed: Palette.black;
            text-color-unpressed: Palette.blue;
        }
      }
    }
    HorizontalLayout {
      x: 0px;
      y: 0px;
      padding-left: 30px;
      padding-right: 24px;
      padding-top: 53px;
      alignment: start;
      width: parent.width;
      height: parent.height;
      VerticalLayout {
        alignment: start;
        vertical-stretch: 1;
        Image {
            source: @image-url("../../../res/img/stellar_logo.png");
            width: 75px;
            height: 75px;
        }
        Spacer {
          height: 10px;
        }
        Text {
            text: "To:";
            font-size: 20px;
            color: black;
            wrap: word-wrap;
            width: 130px;
        }
        Text {
            text: SendStellarState.destination-short;
            font-size: 20px;
            color: black;
            //font-weight: 1000;
            wrap: word-wrap;
            width: 130px;
        }
      }
    }
}