import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { Palette } from "Palette.slint";
import { VerticalBox } from "std-widgets.slint";
import { BaseButton } from "BaseButton.slint";
import { Spacer } from "Spacer.slint";

export enum Protocol {
    Bluetooth,
    NFC
}

export global SendScreenState {
  in-out property <Protocol> current-protocol: Protocol.NFC;
  in-out property <string> error-message;
  in-out property <bool> error-occurred;
  callback protocol-changed();
  callback send-requested();
  send-requested => {
    Router.navigate(ScreenEnum.SendStellar);
  }
}

component TextWithBackground inherits Text {
    in-out property<string> header-title: self.text;
    property <length> text-width: self.width;
    property <length> text-height: self.height;
    in-out property <bool> pressed;
    in-out property <brush> font-color: Palette.blue;
    if header-title != "": Rectangle {
        background: Palette.white;
        width: 1.1 * parent.text-width;
        height: 1.5 * parent.text-height;
        textProp := Text {
            text: header-title;
            font-size: root.font-size;
            font-family: root.font-family;
            font-italic: root.font-italic;
            font-weight: root.font-weight;
            color: pressed ? Palette.black :root.font-color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}

export component SwitchButton {
  property <bool> pressed: false;
  in-out property <string> content: "0";
  in-out property <length> button-width;
  in-out property <length> button-height;
  in-out property <length> in-font-size: 20px;
  in-out property <color> text-color: pressed ? Palette.black : Palette.blue;
  TextWithBackground {
      text: root.content;
      pressed: root.pressed;
      font-size: root.in-font-size;
      color: root.text-color;
      horizontal-alignment: center;
      vertical-alignment: center;
      TouchArea {
      width: parent.width;
      height: parent.height;
      pointer-event(event) => {
          if (event.kind == PointerEventKind.down) {
                  pressed = true;
              } else if (event.kind == PointerEventKind.up) {
                  pressed = false;
                  root.clicked();
                  debug("Clicked pin", content);
              }
          }
      }
    }
    callback clicked();
}

export component SendScreenView {
    width: 320px;
    height: 240px;
    // show-brightness: true; // Show brightness control on home screen
    // header-title: "SEND CRYPTO";
    in property <image> image-src: SendScreenState.current-protocol == Protocol.NFC ? @image-url("../../../res/img/nfc.png") : @image-url("../../../res/img/bt_logo.png");
    in-out property <string> current-protocol-name: SendScreenState.current-protocol == Protocol.NFC ? "NFC" : "Bluetooth";
    in-out property <string> next-protocol-name: SendScreenState.current-protocol == Protocol.NFC ? "Bluetooth" : "NFC";
    HorizontalLayout {
      alignment: center;
      y: 35px;
      VerticalLayout {
        width: 200px;
        Text {
          text: current-protocol-name + " is active";
          font-size: 12px;
          font-family: "Roboto Mono";
          font-italic: false;
          font-weight: 500;
          horizontal-alignment: center;
          wrap: word-wrap;
          color: Palette.black;
          vertical-alignment: center;
          height: 30px;
        }
      }
      visible: !SendScreenState.error-occurred;
    }
    Text {
      width: root.width;
      height: root.height;
      text: SendScreenState.error-message;
      font-size: 20px;
      font-weight: 500;
      horizontal-alignment: center;
      wrap: word-wrap;
      vertical-alignment: center;
      visible: SendScreenState.error-occurred;
    }
    Image {
      source: image-src;
      horizontal-alignment: center;
      vertical-alignment: center;
      visible: !SendScreenState.error-occurred;
    }
    HorizontalLayout {}
    SwitchButton {
        content: "Switch to " + next-protocol-name;
        y: 190px;
        clicked => {
          debug("Switch button clicked");
          SendScreenState.protocol-changed();
          if (SendScreenState.current-protocol == Protocol.NFC) {
              SendScreenState.current-protocol = Protocol.Bluetooth;
          } else {
              SendScreenState.current-protocol = Protocol.NFC;
          }
        }
        visible: !SendScreenState.error-occurred;
    }
}