import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { Palette } from "Palette.slint";
import { VerticalBox } from "std-widgets.slint";
import { Spacer } from "Spacer.slint";
import { TransparentButton } from "TransparentButton.slint";

export enum Protocol {
    Bluetooth,
    NFC
}

export global SendScreenState {
  in-out property <Protocol> current-protocol;
  in-out property <string> error-message;
  in-out property <bool> error-occurred;
  callback protocol-changed();
  callback send-requested();
  send-requested => {
    Router.navigate(ScreenEnum.SendStellar);
  }
}

export component CommunicateScreenView {
    width: 320px;
    height: 240px;
    init => {
      SendScreenState.protocol-changed();
      SendScreenState.current-protocol = Protocol.NFC;
      SendScreenState.error-occurred = false;
      SendScreenState.error-message = "";
    }
    in property <image> image-src: SendScreenState.current-protocol == Protocol.NFC ? @image-url("../../../res/img/nfc.png") : @image-url("../../../res/img/bt_logo.png");
    in-out property <string> current-protocol-name: SendScreenState.current-protocol == Protocol.NFC ? "NFC" : "Bluetooth";
    in-out property <string> next-protocol-name: SendScreenState.current-protocol == Protocol.NFC ? "Bluetooth" : "NFC";
    Text {
      y: 25px;
      text: current-protocol-name + " is active";
      font-size: 12px;
      horizontal-alignment: center;
      wrap: word-wrap;
      color: Palette.black;
      vertical-alignment: center;
      height: 30px;
      visible: !SendScreenState.error-occurred;
    }
    Text {
      width: root.width;
      height: root.height;
      text: SendScreenState.error-message;
      font-size: 20px;
      //font-weight: 500;
      horizontal-alignment: center;
      wrap: word-wrap;
      vertical-alignment: center;
      visible: SendScreenState.error-occurred;
    }
    Image {
      source: image-src;
      horizontal-alignment: center;
      vertical-alignment: center;
      visible: !SendScreenState.error-occurred;
    }
    TransparentButton {
        content: "Switch to " + next-protocol-name;
        text-color-pressed: Palette.black;
        text-color-unpressed: Palette.blue;
        y: 190px;
        clicked => {
          //debug("Switch button clicked");
          SendScreenState.protocol-changed();
          if (SendScreenState.current-protocol == Protocol.NFC) {
              SendScreenState.current-protocol = Protocol.Bluetooth;
          } else {
              SendScreenState.current-protocol = Protocol.NFC;
          }
        }
        visible: !SendScreenState.error-occurred;
    }
}