import { TestScreen2View } from "TestScreen2.slint";
import { Palette } from "Palette.slint";
import { TransparentButton } from "TransparentButton.slint";
import { Spacer } from "Spacer.slint";
import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";

component SettingsOptionButton inherits TransparentButton {
    text-color-pressed: Palette.black;
    text-color-unpressed: Palette.blue;
}

export component SettingsScreenView {
    width: 320px;
    height: 240px;
    VerticalLayout {
        alignment: start;
        y: 35px;
        spacing: 10px;
        width: 240px;
        SettingsOptionButton {
            content: "Pair with the app";
            clicked => {
                Router.navigate(ScreenEnum.PairWithTheApp);
            }
        }
        SettingsOptionButton {
            content: "Show seed phrase";
            clicked => {
                Router.navigate(ScreenEnum.EnterPin);
            }
        }
        SettingsOptionButton {
            content: "Device info";
            clicked => {
                Router.navigate(ScreenEnum.DeviceInfo);
            }
        }
        Spacer { height: 2px; }
        SettingsOptionButton {
            content: "Change passcode";
            clicked => {
                Router.navigate(ScreenEnum.Send);
            }
        }
        SettingsOptionButton {
            content: "Factory reset";
            clicked => {
                Router.navigate(ScreenEnum.Send);
            }
        }
    }
    // Additional UI elements for the Settings screen can be added here
}