import { TestScreen2View } from "TestScreen2.slint";
import { Palette } from "Palette.slint";
import { TransparentButton } from "TransparentButton.slint";
import { Spacer } from "Spacer.slint";
import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";

component SettingsOptionButton inherits TransparentButton {
    text-color-pressed: Palette.black;
    text-color-unpressed: Palette.blue;
}

export component SettingsScreenView {
    width: 320px;
    height: 240px;
    in property <length> button-y: 30px;
    in property <length> button-h: 35px;
    SettingsOptionButton {
        content: "Pair with the app";
        y: button-y;
        clicked => {
            Router.navigate(ScreenEnum.PairWithTheApp);
        }
    }
    SettingsOptionButton {
        content: "Show seed phrase";
        y: button-y + button-h;
        clicked => {
            Router.navigate(ScreenEnum.EnterPin);
        }
    }
    SettingsOptionButton {
        content: "Device info";
        y: button-y + 2 * button-h;
        clicked => {
            Router.navigate(ScreenEnum.DeviceInfo);
        }
    }
    SettingsOptionButton {
        content: "Change passcode";
        y: button-y + 3.5 * button-h ;
        clicked => {
            Router.navigate(ScreenEnum.ChangePasscode);
        }
    }
    SettingsOptionButton {
        content: "Factory reset";
        y: button-y + 4.5 * button-h;
        clicked => {
            Router.navigate(ScreenEnum.Send);
        }
    }
    // Additional UI elements for the Settings screen can be added here
}