import { Palette } from "Palette.slint";
import { TransparentButton } from "TransparentButton.slint";
import { Spacer } from "Spacer.slint";

export global ShowSeedState {
  in-out property <string> seed-phrase-fragment;
  in-out property <int> seed-len;
  in-out property <int> page-number: 0;
  in-out property <bool> all-words-hidden: true;
  in-out property <int> total-pages: 2;
  pure callback get-word(index: int) -> string;
  callback page-changed(page-number: int);
}

component SeedWord inherits Text {
    in-out property <int> index: 0;
    in-out property <bool> word-visible: false;
    in-out property <string> index-str: index + 1 < 10 ? "0" + (index + 1): (index + 1);
    text: self.word-visible ? index-str + "." + ShowSeedState.get-word(index) : "xx.xxxxxxxx";
    font-size: 20px;
    color: Palette.black;
    letter-spacing: -0.5px;
    height: 30px;
    TouchArea {
        width: parent.width;
        height: parent.height;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                ShowSeedState.all-words-hidden = false;
                word-visible = !word-visible;
            } else if (event.kind == PointerEventKind.up) {
                //debug("Clicked pin", root.text);
            }
        }
    }
    visible: index < ShowSeedState.seed-len;
}

export component ShowSeedScreenView {
    width: 320px;
    height: 240px;
    HorizontalLayout {
      x: 20px;
      alignment: start;
      VerticalLayout {
        y: 60px;
        alignment: start;
        width: parent.width / 2;
        SeedWord { index: 0 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 1 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 2 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 3 + ShowSeedState.page-number * 8;  }
      }
    }
    HorizontalLayout {
      x: 10px;
      alignment: end;
      VerticalLayout {
        y: 60px;
        alignment: start;
        width: parent.width / 2;
        SeedWord { index: 4 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 5 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 6 + ShowSeedState.page-number * 8;  }
        SeedWord { index: 7 + ShowSeedState.page-number * 8;  }
        Spacer {
          height: 20px;
        }
        TransparentButton {
          x: -5px;
            content: "Next Page";
            text-color-pressed: Palette.black;
            text-color-unpressed: Palette.blue;
            clicked => {
                if (ShowSeedState.page-number < ShowSeedState.total-pages - 1) {
                    ShowSeedState.page-number += 1;
                } else {
                    ShowSeedState.page-number = 0;
                }
                ShowSeedState.page-changed(ShowSeedState.page-number);
            }
        }
      }
    }
}