import { TransparentButton } from "TransparentButton.slint";
import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { Palette } from "Palette.slint";
export global SignedState {
  callback request-data();
}

export component SignedScreenView {
  width: 320px;
  height: 240px;
  VerticalLayout {
    alignment: end;
    y: -10px;
    TransparentButton {
      content: "DONE";
      text-color-pressed: Palette.black;
      text-color-unpressed: Palette.blue;
      clicked => {
        Router.navigate(ScreenEnum.Home);
      }
    }
  }
}