import { Router } from "Router.slint";
import { ScreenEnum } from "ScreenEnum.slint";
import { BaseButton } from "BaseButton.slint";

export component TestScreenView {
    Text {
        text: "This is a test screen!";
        font-size: 20px;
        color: black;
        horizontal-alignment: center;
        y: 100px;
        x: 22px;
        wrap: word-wrap;
        width: 280px;
    }
    BaseButton {
        x: 70px;
        y: 180px;
        button-width: 100px;
        button-height: 50px;
        content: "Go to Enter PIN";
        clicked() => {
            Router.navigate(ScreenEnum.Home);
        }
    }
}